#!/bin/bash
search_url="https://mangakakalot.com/search/story/"
base_url="https://mangakakalot.com/"
image_dir="$HOME/.cache/manga-cli/"
history_file="$HOME/.cache/manga-cli-hsts"

# File format
file_format="cbz"

# colors
Green='\033[0;32m' 
Yellow='\033[0;33m' 
White='\033[0;37m' 

mangaName="${@: -1}"
prog="$0"


# Commands
ls=/usr/bin/ls


help_text () {
	while IFS= read -r line; do
		printf "%s\n" "$line"
	done <<-EOF
  
	Usage:
        ${prog} [option] 
	Options:
        --pdf  change file format to pdf
        --clear-cache Clears the downloaded files
	EOF
}

search_manga() {

    echo -n -e "${Yellow}Search manga: " 
    read mangaName
    mangaName="${mangaName// /_}"
    mangaName="${mangaName//-/_}"


    mapfile -t mangaNames < <(curl -s "$search_url$mangaName" | pup "div.story_item_right h3 a text{}")
    declare -p mangaNames > /dev/null


    # Manga Ids
    mapfile -t mangaIds < <(curl -s "$search_url$mangaName" | pup "div.story_item_right h3 a attr{href}")
    declare -p mangaIds > /dev/null


    i=1
    for each in "${mangaNames[@]}"
    do
        echo -e "${White}[$i]$each"
        ((i=i+1))
    done

    echo -n -e "${Yellow}Enter Number: "
    read mangaNumber

    mangaNumber=$((mangaNumber-1))
    name=$(echo ${mangaNames[$mangaNumber]})
    name="${name// /_}"
    name=${name//[^[:alnum:]]/}
    mangaLink=$(echo ${mangaIds[$mangaNumber]})


}

select_chapter () {
    echo -n -e "${Yellow}Enter chapter number: "
    read chapterNumber

    get_images "$mangaLink" "$chapterNumber"
		

}


create_file() {
    if [ $file_format == "pdf" ]
    then 
        echo "Converting to pdf..."
        convert $($ls -v $image_dir*.jpg) "$image_dir$name-$chapterNumber.pdf" 
        rm $image_dir/*.jpg
        clear
        zathura "$image_dir$name-$chapterNumber.pdf" &
        choose_next
    else 

        echo "Converting to cbz..."
        zip -q $image_dir$name-$chapterNumber.cbz $image_dir*.jpg

        rm $image_dir/*.jpg
        clear
        zathura "$image_dir$name-$chapterNumber.cbz" &
        choose_next
    fi
}

download_chapter() {


    update_hsts
    exit 0

    clear
    echo -e "${Green}Getting data on the chapters...."
    i=11

    for each in "${chapterImages[@]}"
    do
        curl \
				--silent \
				--create-dirs \
				--header 'Referer: https://readmanganato.com/' \
				--output "$image_dir$name-$i.jpg" \
                "${each}" &

        ((i=i+1))
    done

    wait


    create_file


}


# History 
check_for_entry() {


    manga=$1
    link=""
    chapter=""


    while read line; do
        line=($line)


        if [[ ${line[0]} == "$manga" ]]; then
            open_session=true
            chapter=${line[1]}
            link=${line[2]}

        fi



    done < $history_file
}
update_hsts () {
    manga_name=$1
    chapter_number=$2
    mangaLink=$3


    check_for_entry "death-note"


    if [ $open_session ]; then
        echo "something"
    fi


    if [ ! -f "$history_file" ]; then
        touch $history_file
    fi

    




}



get_images() {
    link=$1
    chNumber=$2


    if [ -f "$image_dir$name-$chNumber.$file_format" ]; then
        clear
        echo -e "${Green}Manga file exists .cache, opening it..."
        zathura "$image_dir$name-$chapterNumber.$file_format" &
        choose_next
    fi




    link="$mangaLink/chapter-$chNumber"

    link2=${mangaLink##*/}
    
    if [[ $mangaLink == *"read-"* ]]; then
        link="https://mangakakalot.com/chapter/$name/chapter_$chNumber"
    elif [[ ! $link2 == *"manga-"* ]]; then
        link="https://mangakakalot.com/chapter/$link2/chapter_$chNumber"
    fi

    mapfile -t chapterImages < <(curl -s "$link" | pup "div.container-chapter-reader img attr{src}")
    # curl -s "$mangaLink/chapter-$mangaNumber" | pup "div.container-chapter-reader img attr{src}"
    declare -p chapterImages > /dev/null





    if [ ! -d "$image_dir" ]; then
        mkdir ~/.cache/manga-cli
    fi
}



choose_next() {
    clear
    echo -e "${White}next chapter ${Green}(n)"
    echo -e "${White}quit ${Green}(q)"
    echo -e "${White}previous chapter ${Green}(p)"

    echo -n -e "${Yellow}Enter Option: "
    read option

    if [ "${option}" = "n" ]
    then
        chapterNumber=$((chapterNumber+1))
        get_images "$mangaLink" "$chapterNumber" 
        download_chapter

    elif [ "${option}" = "p" ]; then
        chapterNumber=$((chapterNumber-1))
        get_images "$mangaLink" "$chapterNumber" 
        download_chapter

    elif [ "${option}" = "q" ]; then
        exit -1

    else 
        choose_next

    fi

}



# Flags
while [ "$1" != "" ]; do
    case $1 in
    -h | --help)
        
        help_text
        exit -1
        ;;
    --pdf)
        
        file_format="pdf"
        download_manga
        exit -1
        ;;

    -c | --clear-cache)
        rm -rf $image_dir
        echo "Cleared cache.."
        exit 1
        ;;
    *)
        ;;
    esac
    shift # remove the current value for `$1` and use the next
done

main () {
    search_manga

    select_chapter

    download_chapter

    choose_next
    clear
}

main

